---
    - apt_key: keyserver='pgp.mit.edu' id=5044912E state=present
    - apt_key: keyserver='hkp://keyserver.ubuntu.com:80' id=0xcbcb082a1bb943db state=present
    - apt_key: keyserver='keyserver.ubuntu.com' id=EEA14886 state=present
    - apt_key: keyserver='keyserver.ubuntu.com' id=A1F196A8 state=present
    - apt_key: keyserver='keyserver.ubuntu.com' id=F24AEA9FB05498B7 state=present
    - apt_key: keyserver='keyserver.ubuntu.com' id=F9CB8DB0 state=present
    - apt_key: url='https://dl-ssl.google.com/linux/linux_signing_key.pub' state=present
    - apt_key: url='http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc' state=present

    - name: Update Sources
      template: src=sources.j2 dest=/etc/apt/sources.list owner=root
    - apt: update_cache=true
