---
-
  name: "Get PHPStorm"
  get_url: "url=http://download.jetbrains.com/webide/PhpStorm-8.0.1.tar.gz dest=/root/PhpStorm-8.0.1.tar.gz"
-
  name: "Unpack PHPStorm"
  unarchive: "src=/root/PhpStorm-8.0.1.tar.gz dest=/root/phpstorm"
-
  name: "Install PHPStorm"
  command: "./phpstorm.sh >> /root/phpstormlog.txt"
  args:
    chdir: /root/phpstorm/bin/
    creates: /root/phpstormlog.txt
